apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ${NAMESPACE}
spec:
  acme:
    email: ${EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory #This is the staging Server from let's encrypt use it when trying things out
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azuredns:
          # Service principal clientId (also called appId)
          clientID: ${AZURE_SERVICE_PRINCIPAL_ID}
          clientSecretSecretRef:
            key: ${PASSWORD}
            name: ${SECRET_NAME}
          # Azure subscription Id
          subscriptionID: ${AZURE_SUBSCRIPTION_ID}
          # Azure AD tenant Id
          tenantID: ${AZURE_TENANT_ID}
          # ResourceGroup name where dns zone is provisioned
          resourceGroupName: ${AZURE_RESOURCE_GROUP}
          # Name of the DNS Zone
          hostedZoneName: ${DOMAIN}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ${CERT_NAME}
  namespace: ${NAMESPACE}
spec:
  secretName: ${CERT_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: '*.${DOMAIN}' 
  dnsNames:
  - ${DOMAIN}
  - '*.${DOMAIN}'
