############################################################################
# Created Date: 08.10.2019                                                 #
# Author: Fabius Engel (fabius.engel@msg.group)                            #
# -----                                                                    #
# Last Modified: 30.10.2019 10:41:14                                       #
# Modified By: Michael Süssemilch (michael.suessemilch@msg.group)          #
# -----                                                                    #
# Copyright (c) 2019 msg nexinsure ag                                      #
############################################################################

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ${NAMESPACE}
spec:
  acme:
    email: ${EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory #This is the staging Server from let's encrypt use it when trying things out
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
      - name: azure-dns
        azuredns:
          email: ${EMAIL}
          # Service principal clientId (also called appId)
          clientID: ${AZURE_SERVICE_PRINCIPAL_ID}
          clientSecretSecretRef:
            key: ${PASSWORD}
            name: ${SECRET_NAME}
          # Azure subscription Id
          subscriptionID: ${AZURE_SUBSCRIPTION_ID}
          # Azure AD tenant Id
          tenantID: ${AZURE_TENANT_ID}
          # ResourceGroup name where dns zone is provisioned
          resourceGroupName: ${AZURE_RESOURCE_GROUP}
          # Name of the DNS Zone
          hostedZoneName: ${DOMAIN}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${CERT_NAME}
  namespace: ${NAMESPACE}
spec:
  secretName: ${CERT_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: '*.${DOMAIN}' 
  dnsNames:
  - ${DOMAIN}
  acme:
    config:
    - dns01:
        provider: azure-dns
        ingressClass: nginx
      domains:
      - '*.${DOMAIN}'
      - ${DOMAIN}
